json.id @user.id
json.email @user.email
json.username @user.username
json.password_digest @user.password_digest
json.age @user.age
json.gender @user.gender
json.city @user.city
json.country @user.country
json.bio @user.bio
json.url @user.url
json.website @user.website
json.support_url @user.support_url
